#!/usr/bin/env python3
"""Export pioneer injection patterns for vault-proxy consumption.

Reads config/injection-patterns.yml via raw text parsing (the source file
uses YAML double-quoted strings with regex backslashes that conflict with
YAML escape rules — the bash scanner parses the same way).

Validates all regexes compile with Python re.compile(), exports minimal
YAML to data/patterns-export.yml.

Usage: python3 scripts/export-patterns.py
"""
import os
import re
import sys

import yaml

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
PATTERNS_FILE = os.path.join(PROJECT_ROOT, "config", "injection-patterns.yml")
EXPORT_FILE = os.path.join(PROJECT_ROOT, "data", "patterns-export.yml")


def parse_patterns(filepath):
    """Parse injection-patterns.yml via raw text extraction.

    Mirrors the bash scanner's approach: read line-by-line, strip quotes,
    extract fields. This avoids YAML escape conflicts in regex strings.
    """
    patterns = []
    current = {}

    with open(filepath) as f:
        for line in f:
            stripped = line.strip()

            if stripped.startswith("- id:"):
                if current.get("id") and current.get("severity") and current.get("regex"):
                    patterns.append(current)
                current = {"id": stripped.split(":", 1)[1].strip()}

            elif stripped.startswith("severity:"):
                current["severity"] = stripped.split(":", 1)[1].strip()

            elif stripped.startswith("regex:"):
                raw = stripped.split(":", 1)[1].strip()
                # Strip surrounding quotes (same as bash scanner)
                if raw.startswith('"') and raw.endswith('"'):
                    raw = raw[1:-1]
                elif raw.startswith("'") and raw.endswith("'"):
                    raw = raw[1:-1]
                current["regex"] = raw

    # Don't forget the last pattern
    if current.get("id") and current.get("severity") and current.get("regex"):
        patterns.append(current)

    return patterns


def main():
    patterns = parse_patterns(PATTERNS_FILE)

    if not patterns:
        print("ERROR: No patterns found in", PATTERNS_FILE, file=sys.stderr)
        sys.exit(1)

    # Validate and extract
    exported = []
    failures = 0

    for p in patterns:
        pid = p["id"]
        severity = p["severity"]
        regex = p["regex"]

        try:
            re.compile(regex)
        except re.error as e:
            print(f"  FAIL: {pid} — {e}", file=sys.stderr)
            failures += 1
            continue

        exported.append({"id": pid, "severity": severity, "regex": regex})

    # Ensure output directory exists
    os.makedirs(os.path.dirname(EXPORT_FILE), exist_ok=True)

    # Write export file with header comment
    header = (
        "# Generated by: make export-patterns\n"
        "# Source: config/injection-patterns.yml\n"
        f"# Count: {len(exported)} patterns\n"
    )
    body = yaml.dump(
        {"patterns": exported},
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )

    with open(EXPORT_FILE, "w") as f:
        f.write(header)
        f.write(body)

    # Report
    print(f"Exported {len(exported)} patterns to {EXPORT_FILE}")
    if failures:
        print(f"WARNING: {failures} pattern(s) failed to compile", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
